import LegalPageTemplate, {
  BulletList,
  BulletItem,
  ContentGrid,
  ContentCard,
  BorderedItem,
  type LegalSection,
} from "@repo/ui/templates/LegalPageTemplate";

const sections: LegalSection[] = [
  {
    id: "vision",
    title: "A Carbon-Neutral Vision for African Aviation",
    variant: "highlight",
    content: (
      <p>
        Klock Aviation is dedicated to leading Africa&apos;s aviation industry
        toward a carbon-neutral future. Our carbon offset program is designed to
        offset emissions generated by our operations and to directly support
        projects that benefit African communities and ecosystems. Through
        strategic partnerships, community initiatives, and sustainable aviation
        practices, we&apos;re committed to environmental responsibility across
        our operations.
      </p>
    ),
  },
  {
    id: "offset-program",
    title: "Our Carbon Offset Program",
    content: (
      <>
        <BorderedItem title="Calculating and Offsetting Emissions">
          We monitor and track emissions from all flights and ground operations
          to ensure accurate data collection. With our goal of carbon
          neutrality, we partner with verified organizations, including Gold
          Standard and Verra, to invest in high-impact projects across Africa.
        </BorderedItem>
      </>
    ),
  },
  {
    id: "projects",
    title: "Projects We Support",
    content: (
      <>
        <p className="mb-6">
          We prioritize initiatives that directly support Africa&apos;s
          communities and ecosystems, including:
        </p>
        <ContentGrid columns={2}>
          <ContentCard title="🌳 Reforestation" variant="gold">
            Restoring forests that absorb CO₂ and provide natural habitats for
            wildlife across African ecosystems.
          </ContentCard>
          <ContentCard title="🍳 Clean Cookstoves" variant="gold">
            Reducing household emissions through clean technology distribution
            to communities throughout Africa.
          </ContentCard>
          <ContentCard title="⚡ Renewable Energy" variant="gold">
            Supporting solar and wind projects that decrease reliance on fossil
            fuels and bring clean energy to underserved areas.
          </ContentCard>
          <ContentCard title="🦁 Biodiversity Conservation" variant="gold">
            Protecting vital ecosystems that contribute to climate resilience
            and preserve Africa&apos;s natural heritage.
          </ContentCard>
        </ContentGrid>
      </>
    ),
  },
  {
    id: "practices",
    title: "Sustainable Practices at Klock Aviation",
    variant: "dark",
    content: (
      <>
        <ContentGrid columns={2}>
          <ContentCard title="Operational Efficiency" variant="dark">
            We optimize flight routes, invest in fuel-efficient aircraft, and
            train our crews in fuel-saving practices to reduce emissions at
            every stage of operations.
          </ContentCard>
          <ContentCard title="Green Technology Investment" variant="dark">
            As part of our future goals, we actively explore sustainable
            aviation fuel (SAF), electric, and hybrid aircraft technologies that
            support our carbon-neutral objectives.
          </ContentCard>
        </ContentGrid>
      </>
    ),
  },
  {
    id: "transparency",
    title: "Stakeholder Engagement and Transparency",
    content: (
      <>
        <ContentGrid columns={2}>
          <BorderedItem title="Transparency in Sustainability">
            Each year, we publish a detailed sustainability report that
            highlights our progress and emissions reductions. Our customers also
            have the option to contribute to offset programs with each booking,
            knowing their impact is felt in the communities we serve.
          </BorderedItem>
          <BorderedItem title="Community and Environmental Partnerships">
            We work with local communities to support conservation and renewable
            energy projects that improve resilience and empower sustainable
            livelihoods across Africa.
          </BorderedItem>
        </ContentGrid>
      </>
    ),
  },
  {
    id: "offset-fund",
    title: "The Klock Aviation Carbon Offset Fund",
    variant: "bordered",
    content: (
      <p>
        To sustain our long-term commitment to carbon neutrality, we&apos;ve
        established a dedicated Carbon Offset Fund, investing a percentage of
        revenue and inviting impact-focused investors to join us in this
        journey. This fund enables us to continually support impactful
        environmental projects and monitor our progress toward a sustainable
        future.
      </p>
    ),
  },
  {
    id: "community",
    title: "Community Service and Sustainability Initiatives",
    variant: "highlight",
    content: (
      <p>
        Klock Aviation is committed to positively impacting African communities
        and the environment through a comprehensive Community Service
        Responsibility (CSR) program. Aligned with our mission of sustainable
        growth and community empowerment, our CSR initiatives focus on
        education, environmental stewardship, infrastructure development,
        cultural promotion, and youth engagement.
      </p>
    ),
  },
  {
    id: "initiatives",
    title: "Key Initiatives",
    content: (
      <>
        <ContentGrid columns={2}>
          <ContentCard title="1. Aviation Education and Training">
            <p className="mb-3">
              We invest in Africa&apos;s future by creating educational
              opportunities in aviation:
            </p>
            <BulletList>
              <BulletItem>
                Scholarships for students pursuing aviation, engineering, and
                technical careers
              </BulletItem>
              <BulletItem>
                Youth Aviation Camps to inspire and educate young people
              </BulletItem>
              <BulletItem>
                Apprenticeship and Internship Programs providing hands-on
                training
              </BulletItem>
            </BulletList>
          </ContentCard>
          <ContentCard title="2. Environmental Conservation">
            <p className="mb-3">
              Klock Aviation actively supports environmental sustainability:
            </p>
            <BulletList>
              <BulletItem>
                Tree-Planting Campaigns to restore local ecosystems
              </BulletItem>
              <BulletItem>
                Biodiversity Conservation Projects protecting endangered species
              </BulletItem>
              <BulletItem>
                Eco-Awareness Programs engaging communities in sustainable
                practices
              </BulletItem>
            </BulletList>
          </ContentCard>
          <ContentCard title="3. Cultural Heritage and Tourism">
            <p className="mb-3">
              We celebrate and promote Africa&apos;s cultural diversity:
            </p>
            <BulletList>
              <BulletItem>
                Local Artisan Partnerships showcasing African art and crafts
              </BulletItem>
              <BulletItem>
                Sustainable Tourism Campaigns encouraging responsible travel
              </BulletItem>
              <BulletItem>
                Cultural Festival Sponsorships supporting African heritage
              </BulletItem>
            </BulletList>
          </ContentCard>
          <ContentCard title="4. STEM Education for Youth">
            <p className="mb-3">To inspire the next generation of innovators:</p>
            <BulletList>
              <BulletItem>
                STEM School Partnerships providing resources and training
              </BulletItem>
              <BulletItem>
                Aviation Innovation Challenge with scholarships for winners
              </BulletItem>
              <BulletItem>
                Women in Aviation Programs empowering young women through
                mentorship
              </BulletItem>
            </BulletList>
          </ContentCard>
          <ContentCard title="5. Employee Volunteering">
            <p className="mb-3">Our team actively engages in community service:</p>
            <BulletList>
              <BulletItem>
                Paid Volunteer Days for employees to support local initiatives
              </BulletItem>
              <BulletItem>
                Community Engagement Days with collaborative projects
              </BulletItem>
              <BulletItem>
                Skills-Based Volunteering sharing expertise with local
                organizations
              </BulletItem>
            </BulletList>
          </ContentCard>
          <ContentCard title="6. Sustainability Awareness">
            <p className="mb-3">
              We educate and involve the public in responsible aviation:
            </p>
            <BulletList>
              <BulletItem>
                Public Awareness Campaigns promoting sustainability
              </BulletItem>
              <BulletItem>
                Community Open Days showcasing our environmental efforts
              </BulletItem>
              <BulletItem>
                Annual Sustainability Report detailing our impact and progress
              </BulletItem>
            </BulletList>
          </ContentCard>
        </ContentGrid>
      </>
    ),
  },
  {
    id: "approach",
    title: "Our Approach to Community Service",
    content: (
      <p>
        Klock Aviation believes in transparent, impactful community engagement
        that embodies African values. By working with local partners and
        actively involving customers, we&apos;re building a sustainable future
        that enhances Africa&apos;s aviation industry and fosters local growth.
      </p>
    ),
  },
  {
    id: "join",
    title: "Join Us in Making a Difference",
    variant: "highlight",
    content: (
      <>
        <p className="mb-4">
          Together, we can empower communities and promote responsible aviation.
          Follow our journey and contribute to our mission to elevate
          Africa&apos;s skies for generations to come.
        </p>
        <p className="text-[#D7B46A] font-medium">
          Through these efforts, Klock Aviation is setting new standards for
          responsible growth, empowering African communities, and advancing
          Africa&apos;s role in the global aviation industry with a commitment
          to environmental responsibility.
        </p>
      </>
    ),
  },
];

export default function SustainabilityPage() {
  return (
    <LegalPageTemplate
      title="Sustainability &amp; ESG Initiatives"
      subtitle="To support Klock Aviation's vision and mission of becoming a leading force in sustainable African aviation, our carbon offset program serves as a core pillar of our environmental responsibility strategy."
      lastUpdated="January 2026"
      sections={sections}
    />
  );
}